version: "3.8"
services:
  loctio_ue_armv6l:
    image: ${ECR}/loctio/ue_armv6l:latest
    container_name: loctio_ue
    restart: always
    mac_address: ${MAC_ADDRESS}
    environment:
    - LOGLEVEL=INFO
    - SAMPLE_AS_BINARY=1
    - MQTT_BROKER_IP=${CLOUD_API_HOST}
    - MQTT_BROKER_PORT=1883
    - TOKEN=${TOKEN}
    - LD_LIBRARY_PATH=resources/executables/raspbian/
    - COMMAND_TO_GET_SAMPLE=resources/executables/raspbian/rtl_sdr
    - COMMAND_TO_GET_SAMPLE_ARG_CAPTURE_FREQ=-f
    - COMMAND_TO_GET_SAMPLE_ARG_SAMPLING_FREQ=-s
    - COMMAND_TO_GET_SAMPLE_ARG_SAMPLES_NUM=-n
    - COMMAND_TO_COMPRESS_SAMPLE=resources/executables/raspbian/msbCompress
    - COMMAND_TO_BIAST=resources/executables/raspbian/rtl_biast
    - COMMAND_TO_BIAST_ARG=-b
    - COMMAND_TO_BIAST_FLAG=1
    devices:
    - "${RTL_SDR_BUS}:${RTL_SDR_BUS}"
    volumes:
    - /tmp:/tmp
    # dynamic linker is needed inside docker in RPI Zero (strings rtl_biast | head -1)
    - /usr/lib/arm-linux-gnueabihf/libstdc++.so.6:/usr/lib/arm-linux-gnueabihf/libstdc++.so.6
    - /lib/ld-linux-armhf.so.3:/lib/ld-linux-armhf.so.3
    - /lib/arm-linux-gnueabihf/:/lib/arm-linux-gnueabihf/

  loctio_ue_armv7l:
    image: ${ECR}/loctio/ue_armv7l:latest
    container_name: loctio_ue
    restart: always
    mac_address: ${MAC_ADDRESS}
    environment:
    - LOGLEVEL=INFO
    - SAMPLE_AS_BINARY=1
    - MQTT_BROKER_IP=${CLOUD_API_HOST}
    - MQTT_BROKER_PORT=1883
    - TOKEN=${TOKEN}
    - LD_LIBRARY_PATH=resources/executables/raspbian/
    - COMMAND_TO_GET_SAMPLE=resources/executables/raspbian/rtl_sdr
    - COMMAND_TO_GET_SAMPLE_ARG_CAPTURE_FREQ=-f
    - COMMAND_TO_GET_SAMPLE_ARG_SAMPLING_FREQ=-s
    - COMMAND_TO_GET_SAMPLE_ARG_SAMPLES_NUM=-n
    - COMMAND_TO_COMPRESS_SAMPLE=resources/executables/raspbian/msbCompress
    - COMMAND_TO_BIAST=resources/executables/raspbian/rtl_biast
    - COMMAND_TO_BIAST_ARG=-b
    - COMMAND_TO_BIAST_FLAG=1
    devices:
    - "${RTL_SDR_BUS}:${RTL_SDR_BUS}"
    volumes:
    - /tmp:/tmp
